#include<stdio.h>
#define P printf
int main(){
    int a,b,c,d,e,f;
    printf("enter a , b , c , d , e & f:\n");
    scanf("%d %d %d %d %d %d",&a,&b,&c,&d,&e,&f);
    (a>b)
        ?(a>c)
            ?(a>d)
                ?(a>e)
                    ?(a>f)
                        ? P("a is big")
                        : P("f is big")
                    :(e>f)
                        ? P("e is big")
                        : P("f is big")
                :(d>e)
                    ?(d>f)
                        ? P("d is big")
                        : P("f is big")
                    :(e>f)
                        ? P("e is big")
                        : P("f is big")
            :(c>d)
                ?(c>e)
                    ?(c>f)
                        ? P("c is big")
                        : P("f is big")
                    :(e>f)
                        ? P("e is big")
                        : P("f is big")
                :(d>e)
                    ?(d>f)
                        ? P("d is big")
                        : P("f is big")
                    :(e>f)
                        ? P("e is big")
                        : P("f is big")
        :(b>c)
            ?(b>d)
                ?(b>e)
                    ?(b>f)
                        ? P("b is big")
                        : P("f is big")
                    :(e>f)
                        ? P("e is big")
                        : P("f is big")
                :(d>e)
                    ?(d>f)
                        ? P("d is big")
                        : P("f is big")
                    :(e>f)
                        ? P("e is big")
                        : P("f is big")
            :(c>d)
                ?(c>e)
                    ?(c>f)
                        ? P("c is big")
                        : P("f is big")
                    :(e>f)
                        ? P("e is big")
                        : P("f is big")
                :(d>e)
                    ?(d>f)
                        ? P("d is big")
                        : P("f is big")
                    :(e>f)
                        ? P("e is big")
                        : P("f is big");
}