#include<stdio.h>
#define P printf
int main(){
    int a,b,c,d,e,f,g;
    P("enter a , b , c , d , e , f & g:\n");
    scanf("%d %d %d %d %d %d %d",&a,&b,&c,&d,&e,&f,&g);
    // seven numbers comperison
    (a>b)
        ?(a>c)
            ?(a>d)
                ?(a>e)
                    ?(a>f)
                        ?(a>g)
                            ?P("a is big")
                            :P("g is big")
                        :(f>g)
                            ?P("f is big")
                            :P("g is big")
                    :(e>f)
                        ?(e>g)
                            ?P("e is big")
                            :P("g is big")
                        :(f>g)
                            ?P("f is big")
                            :P("g is big")
                :(d>e)
                    ?(d>f)
                        ?(d>g)
                            ?P("d is big")
                            :P("g is big")
                        :(f>g)
                            ?P("f is big")
                            :P("g is big")
                    :(e>f)
                        ?(e>g)
                            ?P("e is big")
                            :P("g is big")
                        :(f>g)
                            ?P("f is big")
                            :P("g is big")
            :(c>d)
                ?(c>e)
                    ?(c>f)
                        ?(c>g)
                            ?P("c is big")
                            :P("g is big")
                        :(f>g)
                            ?P("f is big")
                            :P("g is big")
                    :(e>f)
                        ?(e>g)
                            ?P("e is big")
                            :P("g is big")
                        :(f>g)
                            ?P("f is big")
                            :P("g is big")
                :(d>e)
                    ?(d>f)
                        ?(d>g)
                            ?P("d is big")
                            :P("g is big")
                        :(f>g)
                            ?P("f is big")
                            :P("g is big")
                    :(e>f)
                        ?(e>g)
                            ?P("e is big")
                            :P("g is big")
                        :(f>g)
                            ?P("f is big")
                            :P("g is big")
        :(b>c)
            ?(b>d)
                ?(b>e)
                    ?(b>f)
                        ?(b>g)
                            ?P("b is big")
                            :P("g is big")
                        :(f>g)
                            ?P("f is big")
                            :P("g is big")
                    :(e>f)
                        ?(e>g)
                            ?P("e is big")
                            :P("g is big")
                        :(f>g)
                            ?P("f is big")
                            :P("g is big")
                :(d>e)
                    ?(d>f)
                        ?(d>g)
                            ?P("d is big")
                            :P("g is big")
                        :(f>g)
                            ?P("f is big")
                            :P("g is big")
                    :(e>f)
                        ?(e>g)
                            ?P("e is big")
                            :P("g is big")
                        :(f>g)
                            ?P("f is big")
                            :P("g is big")
            :(c>d)
                ?(c>e)
                    ?(c>f)
                        ?(c>g)
                            ?P("c is big")
                            :P("g is big")
                        :(f>g)
                            ?P("f is big")
                            :P("g is big")
                    :(e>f)
                        ?(e>g)
                            ?P("e is big")
                            :P("g is big")
                        :(f>g)
                            ?P("f is big")
                            :P("g is big")
                :(d>e)
                    ?(d>f)
                        ?(d>g)
                            ?P("d is big")
                            :P("g is big")
                        :(f>g)
                            ?P("f is big")
                            :P("g is big")
                    :(e>f)
                        ?(e>g)
                            ?P("e is big")
                            :P("g is big")
                        :(f>g)
                            ?P("f is big")
                            :P("g is big");

}